# Generated by Django 3.1.4 on 2020-12-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='location',
            new_name='s3_location',
        ),
    ]
