# Generated by Django 3.1.4 on 2020-12-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20201206_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='photo',
            field=models.ImageField(default='none', upload_to=''),
            preserve_default=False,
        ),
    ]
