# Generated by Django 3.1.4 on 2020-12-11 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='photo',
            new_name='raw_image',
        ),
    ]
